version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    networks:
      - nodenet
    volumes:
      - ./app:/usr/src/app
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /docker-entrypoint-initdb.d/setup.sql
    container_name: db
    tty: true
    volumes:
      - ./mysql/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: nervado/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  nodenet:
    driver: bridge
