version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: nervado/app:prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    networks:
      - nodenet
      - sqlnet
    tty: true
    depends_on:
      - db
  db:
    build:
      context: ./mysql
    image: nervado/mysql:prod
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - sqlnet
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: nervado/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  nodenet:
    driver: bridge
  sqlnet:
    driver: bridge
